# Generated by Django 2.2.5 on 2019-09-11 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=50)),
                ('concept_overview', models.CharField(max_length=1000)),
                ('concept_key', models.CharField(max_length=1000)),
                ('contents_aim', models.CharField(max_length=1000)),
                ('conflict_company', models.CharField(max_length=1000)),
                ('main_terget', models.CharField(max_length=1000)),
                ('concept_background', models.CharField(max_length=1000)),
                ('suitable_communication', models.CharField(max_length=1000)),
                ('product_feature', models.CharField(max_length=1000)),
                ('key_messages', models.CharField(max_length=1000)),
                ('free_words', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('task_taker', models.CharField(max_length=50)),
                ('client_industry', models.CharField(max_length=50)),
                ('client_rank', models.CharField(max_length=10)),
                ('old_plan_url', models.CharField(blank=True, max_length=100)),
                ('output_num', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanOverView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.CharField(max_length=20)),
                ('plan_num', models.IntegerField()),
                ('breif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgblog.Breif')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgblog.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=1000)),
                ('client_information', models.CharField(max_length=1000)),
                ('points_to_remember', models.CharField(max_length=1000)),
                ('target_reader', models.CharField(max_length=1000)),
                ('target_issue', models.CharField(max_length=1000)),
                ('why_good_issue', models.CharField(max_length=1000)),
                ('solution_for_issue', models.CharField(max_length=1000)),
                ('why_good_solution', models.CharField(max_length=1000)),
                ('keywords', models.CharField(max_length=1000)),
                ('blog_summary', models.CharField(max_length=1000)),
                ('blog_construct', models.CharField(max_length=1000)),
                ('blog_good_points', models.CharField(max_length=1000)),
                ('blog_title', models.CharField(max_length=1000)),
                ('blog_merit_to_read', models.CharField(max_length=1000)),
                ('blog_biginning', models.CharField(max_length=1000)),
                ('why_good_beginning', models.CharField(max_length=1000)),
                ('free_words_for_writer', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_creative_brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgblog.Breif')),
                ('plan_overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgblog.PlanOverView')),
            ],
        ),
        migrations.AddField(
            model_name='breif',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mgblog.Client'),
        ),
    ]
