# Generated by Django 2.2.5 on 2019-09-08 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mgblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planoverview',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mgblog.Client'),
        ),
    ]
