# Generated by Django 2.2.5 on 2019-09-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgblog', '0003_auto_20190908_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoverview',
            name='client_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
